"""
Django settings for MEPBE project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-@1d^plknc3q+c=mm#bqf53tpx!0&2t0p@l+_=x^#7gi1y7d(qy"

DEBUG = True

ALLOWED_HOSTS = [
    "forooghteb.ir",
    ".forooghteb.ir",
    "127.0.0.1",
    "localhost",
]


# ====================
# INSTALLED APPS
# ====================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "corsheaders",

    # My Apps
    "login",
    "api",
    "Products",
    "rest_framework",
]


# ====================
# MIDDLEWARE
# ====================
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "MEPBE.urls"


# ====================
# TEMPLATES
# ====================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "MEPBE.wsgi.application"


# ====================
# DATABASE
# ====================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ====================
# AUTH
# ====================
AUTH_USER_MODEL = "login.User"

AUTHENTICATION_BACKENDS = [
    "login.backends.EmailBackend",
]


# ====================
# REST FRAMEWORK
# ====================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}


# ====================
# CORS (FrontEnd Access)
# ====================
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    "https://forooghteb.ir",
    "https://www.forooghteb.ir",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]


# ====================
# STATIC & MEDIA
# ====================
STATIC_URL = "/static/"
MEDIA_URL = "/media/"

STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / "Products" / "media"


# ====================
# CSRF
# ====================
CSRF_TRUSTED_ORIGINS = [
    "https://forooghteb.ir",
    "https://www.forooghteb.ir",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
