"""
Django settings for MEPBE project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import os


BASE_DIR = Path(__file__).resolve().parent.parent


# ====================
# ENVIRONMENT
# ====================

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-development-secret-key"
)


DEBUG = os.getenv(
    "DJANGO_DEBUG",
    "false"
).lower() == "true"


ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        "localhost,127.0.0.1"
    ).split(",")
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# ====================
# INSTALLED APPS
# ====================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "corsheaders",

    # My Apps
    "login",
    "api",
    "Products",

    "rest_framework",
]


# ====================
# MIDDLEWARE
# ====================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    "whitenoise.middleware.WhiteNoiseMiddleware",

    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "MEPBE.urls"


# ====================
# TEMPLATES
# ====================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "MEPBE.wsgi.application"



# ====================
# DATABASE
# ====================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",

        "NAME": os.getenv(
            "POSTGRES_DB",
            "medical_db"
        ),

        "USER": os.getenv(
            "POSTGRES_USER",
            "medical_user"
        ),

        "PASSWORD": os.getenv(
            "POSTGRES_PASSWORD",
            ""
        ),

        "HOST": os.getenv(
            "POSTGRES_HOST",
            "db"
        ),

        "PORT": os.getenv(
            "POSTGRES_PORT",
            "5432"
        ),
    }
}



# ====================
# AUTH
# ====================

AUTH_USER_MODEL = "login.User"


AUTHENTICATION_BACKENDS = [
    "login.backends.EmailBackend",
]



# ====================
# REST FRAMEWORK
# ====================

REST_FRAMEWORK = {

    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],

    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],

    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],

    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
}



# ====================
# CORS
# ====================

CORS_ALLOW_ALL_ORIGINS = False


CORS_ALLOWED_ORIGINS = [

    "https://forooghteb.ir",
    "https://www.forooghteb.ir",

    "http://localhost:3000",
    "http://127.0.0.1:3000",
]



# ====================
# STATIC & MEDIA
# ====================

STATIC_URL = "/static/"

MEDIA_URL = "/media/"


STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_ROOT = BASE_DIR / "Products" / "media"



# ====================
# CSRF
# ====================

CSRF_TRUSTED_ORIGINS = [

    "https://forooghteb.ir",
    "https://www.forooghteb.ir",

    "http://localhost:3000",
    "http://127.0.0.1:3000",
]



# ====================
# DEFAULT PRIMARY KEY
# ====================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
