import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import localFont from "next/font/local"
import "./globals.css";
import Logo from "../public/favicon.ico"

import Navbar from "../Components/Navbar";

const vazirmatn = Vazirmatn({
  variable: "--font-main",
  subsets: ["latin"],
});

const yekan = localFont({
  src : "../font/w_Yekan.ttf",
  display: 'swap',
})

export const metadata: Metadata = {
  title : {
    default : "تجهیزات پزشکی ",
    template: "%s | "
  },
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: Logo.src,
        sizes: "32x32",
        type: "image/x-icon"
      }
    ]
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${vazirmatn.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
