import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import localFont from "next/font/local"
import "./globals.css";

const vazirmatn = Vazirmatn({
  variable: "--font-main",
  subsets: ["latin"],
});

const yekan = localFont({
  src : "./font/w_Yekan.ttf",
  display: 'swap',
})

export const metadata: Metadata = {
  title : {
    default : "تجهیزات پزشکی ",
    template: "%s | "
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${vazirmatn.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
