import type { Metadata } from "next";
import "./globals.css";
import Logo from "../public/favicon.ico"
import Navbar from "../Components/Navbar";
import localFont from 'next/font/local';

const Vazirmatn = localFont({
  src: [
    { path: '../font/Vazirmatn-Regular.ttf', weight: '400' },
    { path: '../font/Vazirmatn-Bold.ttf', weight: '700' },
  ],
  display: 'swap',
});

export const metadata: Metadata = {
  title : {
    default : "تجهیزات پزشکی ",
    template: "%s | "
  },
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: Logo.src,
        sizes: "32x32",
        type: "image/x-icon"
      }
    ]
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={Vazirmatn.className}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
