# Generated by Django 5.2.4 on 2025-07-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
