# Generated by Django 5.2.4 on 2025-07-26 23:50

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_user_slug"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
