# Generated by Django 5.2.4 on 2025-07-27 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
