# Generated by Django 5.2.4 on 2025-08-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
