# Generated by Django 5.2.4 on 2025-08-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0004_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
