# Generated by Django 5.2.4 on 2025-08-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0005_alter_product_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
