# Generated by Django 5.2.4 on 2025-08-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0006_alter_product_options_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/images/"
            ),
        ),
    ]
