# Generated by Django 5.2.4 on 2025-08-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0007_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
